# Generated by Django 6.0.4 on 2026-07-30 20:22

import dewey.django.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationEntry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dewey.django.models.new_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("channel", models.CharField(db_index=True, max_length=50)),
                ("recipient", models.CharField(max_length=500)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=dewey.django.models.utcnow),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_entries",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["scheduled_for"],
                        name="ix_notif_pending_sched",
                    ),
                    models.Index(
                        condition=models.Q(("status", "sending")),
                        fields=["updated_at"],
                        name="ix_notif_sending_ua",
                    ),
                    models.Index(
                        condition=models.Q(("status", "failed")),
                        fields=["scheduled_for"],
                        name="ix_notif_failed_sched",
                    ),
                    models.Index(fields=["task_id", "created_at"], name="ix_notif_task_created_dj"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskEntry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dewey.django.models.new_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatching", "Dispatching"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("queue", models.CharField(default="default", max_length=50)),
                ("priority", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=dewey.django.models.utcnow),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("dispatching_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "task_entries",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["scheduled_for"],
                        name="ix_task_pending_sched",
                    ),
                    models.Index(
                        condition=models.Q(("status", "dispatching")),
                        fields=["dispatching_at"],
                        name="ix_task_dispatching",
                    ),
                    models.Index(
                        condition=models.Q(("status", "processing")),
                        fields=["started_at"],
                        name="ix_task_processing_started",
                    ),
                    models.Index(
                        condition=models.Q(("status", "failed")),
                        fields=["scheduled_for"],
                        name="ix_task_failed_sched",
                    ),
                    models.Index(fields=["task_type", "created_at"], name="ix_task_type_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_type", "idempotency_key"), name="uq_task_type_idempotency_key"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationAttempt",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dewey.django.models.new_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("error", models.TextField(blank=True, default="")),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=dewey.django.models.utcnow)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="dewey.notificationentry",
                    ),
                ),
            ],
            options={
                "db_table": "notification_attempts",
                "indexes": [
                    models.Index(
                        fields=["notification", "attempt_number"], name="ix_notif_attempt_num_dj"
                    )
                ],
            },
        ),
    ]
