# Generated by Django 6.0.7 on 2026-08-05 14:11

import dewey.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskEntry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=dewey.django.models.new_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatching", "Dispatching"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("queue", models.CharField(default="default", max_length=50)),
                ("priority", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=dewey.django.models.utcnow),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("dispatching_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "task_entries",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["scheduled_for"],
                        name="ix_task_pending_sched",
                    ),
                    models.Index(
                        condition=models.Q(("status", "dispatching")),
                        fields=["dispatching_at"],
                        name="ix_task_dispatching",
                    ),
                    models.Index(
                        condition=models.Q(("status", "processing")),
                        fields=["started_at"],
                        name="ix_task_processing_started",
                    ),
                    models.Index(
                        condition=models.Q(("status", "failed")),
                        fields=["scheduled_for"],
                        name="ix_task_failed_sched",
                    ),
                    models.Index(fields=["task_type", "created_at"], name="ix_task_type_created"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task_type", "idempotency_key"), name="uq_task_type_idempotency_key"
                    )
                ],
            },
        ),
    ]
